name: Upload to IPFS

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to IPFS using public gateway
        uses: pl-strflt/ipfs-upload-action@v1
        with:
          path: jinnz2-archive-1.zip
